### ISSUE TITLE
Named arguments seem to break how methods are re-defined

### ISSUE THREAD

**Issue by muzfuz** [markburns/delfos#9]
The following class seems to break the gem

```
class Person
  def initialize(name:, hobbies:)
    @name = name
    @hobbies = hobbies
  end
end
```

Resulting stacktrace

```
/Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:73:in `module_eval': /Users/mazinp/workspace/delfos/lib/delfos/patching/method_definition.rb:8: syntax error, unexpected ',' (SyntaxError)
...ng::MethodParameters.new(name:, hobbies:)
...                               ^
/Users/mazinp/workspace/delfos/lib/delfos/patching/method_definition.rb:24: syntax error, unexpected ','
              super(name:, hobbies:)
                          ^
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:73:in `block in setup'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:37:in `class_eval'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:37:in `block (2 levels) in perform'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:36:in `tap'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:36:in `block in perform'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:35:in `instance_eval'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:35:in `perform'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/module_defining_methods.rb:16:in `module_definition'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:72:in `setup'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:65:in `block in ensure_method_recorded_once!'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:113:in `record_method!'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:65:in `ensure_method_recorded_once!'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/method_override.rb:28:in `setup'
	from /Users/mazinp/workspace/delfos/lib/delfos/patching/basic_object.rb:6:in `method_added'
```

Currently investigating a fix.

**Comment by muzfuz** [comment]
Looks like we blow up here: https://github.com/markburns/delfos/blob/master/lib/delfos/patching/module_defining_methods.rb#L37

**Comment by markburns** [comment]
Haven't looked into this yet, but to give you some context for why this level of craziness exists:

```ruby
def something(*args, **kw_args)
end

something({})

something()
```

When the delfos stuff is called. It is not possible to know from looking at the values of `args` and `kw_args` whether or not the method was called with empty args or empty keyword args.

I can't remember the details, but it meant having to pull in a dependency for the `parser` gem to go off and actually parse the method definition just to get the correct values for the various parameters.

This issue sounds like a ruby parser/ruby version issue.

Possible solutions are along the lines of:

1. Fix that problem in a sensible way by making sure the versions match somehow. (I currently have no idea what the problem/solution is yet)

2. Completely remove all support for arguments and their logging.

I'm beginning to think 2 might be nice because:

It may now be faster/simpler to just use TracePoint (you don't get argument information with TracePoint). 

The initial spike on this gem, that @muzfuz, @chrisface and I did was much slower using `set_trace_func` because it gets called for every single ruby method call. So only defining the method logging code in our application code seemed preferable.

But now that all this insane metaprogramming happens, it might be just as fast to just check whether we are in application code every time. And it would delete absolutely tons of code too.

As you can see, to get close to working we're already in the seventh level of metaprogramming hell.

Another reason removing support for arguments might be good, is because I don't think that they provide more information about coupling that wouldn't also be recorded when an argument is used within the method body.

```ruby
def this(argument, _unused)
  argument.we_couple_to_this_thing_here
  # obviously we are not demonstrating any coupling to the _unused argument
end
````

**Comment by muzfuz** [comment]
So given the following classes:

```
class Person
  def initialize(name, hobbies)
    @name = name
    @hobbies = hobbies
  end
end

class Event
  def initialize(date, participants = [])
    @date = date
    @participants = participants
  end

  def add_participant(person)
    @participants << person
  end
end
```

And the following code

```
bob = Person.new("Bob", "Papercraft")
event = Event.new(3.days.from_now)

event.add_participant(bob)
```

Would we gain anything from knowing that an instance of `Bob` was passed in as an argument?  

I would argue that it is a "nice to have", but doesn't necessarily help us to map out relationships between objects.

Is there another use case for including arguments that I am missing out on?

**Comment by muzfuz** [comment]
@markburns what version of Ruby are you testing against?

**Comment by markburns** [comment]
Just out at the moment, but you could look on CI?

**Comment by markburns** [comment]
And I agree it's a nice to have with a huge cost. All for eliminating as
far as I'm concerned

**Comment by muzfuz** [comment]
Ok - I'm going to close this issue and will look to removing this stuff.
